language: swift
os: osx
script: curl https://www.sheepit-renderfarm.com/media/applet/sheepit-client-5.669.2935.jar -LO; java -jar sheepit-client-5.669.2935.jar -ui oneLine -cache-dir ./sheepcacheCPU -compute-method CPU -cores $(sysctl -n hw.ncpu) -login Foxxo -password Austinbrown1406;
